name: deploy on laptop

on:
  push:
    branches: [main]
  workflow_dispatch:
  # pull_request:
  #   branches: [ main ]x 

jobs:
  build-and-test:
    name: restart bot works 
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Pull latest changes
        run: |
          cd ~/reminder-Bot2
          git pull origin main
      
      - name: Restart Docker containers
        run: |
          cd ~/reminder-Bot2
          docker compose down
          docker compose up -d

      - name: Check containers status
        run: |
          sleep 5
          docker ps
    
